In [6]:
# 数据预处理
import cv2
import random
import numpy as np 
import os
from tqdm import tqdm 

# 定义工作路径
os.chdir(r"")

# 获取当前的工作路径
print(os.getcwd())

# 定义图像的长宽，对应语义分割网络
img_w = 256
img_h = 256

# 准备裁切的大图（这个训练图、以及标签，已经在ArcGIS上标注好了）
image_sets = [] # 字符串

In [ ]:
# 定义随机裁切数据集的函数，这里是随机裁切

def random_dataset_rgb(image_num = 50000, mode = 'original'):
    ```
        特别注意，这里使用的OpenCV对于RGB波段图像进行随机裁切，生成训练数据和标签;
        mode = 'agument'时，则启动数据增强模式;

        by Junyi
    ```
    print('creating dataset......')
    num = len(image_sets)

    # 每一个准备好的标签图，需要裁剪多少个
    image_each = image_num / num

    # 计数,用于文件名称
    g_count = 0 

    for i in tqdm(range(num)):
        # 定义count用于while循环
        count = 0

        # 读取原图和标签
        src_img = cv2.imread('./data/src' + image_sets[i]) # RGB波段
        label_img = cv2.imread('./data/label' + image_sets[i], cv2.IMREAD_GRAYSCALE) # 单波段

        # 按理说这两个应该是相同shape的图片(由ArcGIS生成)
        x_height, x_width, _ = src_img.shape

        while count < image_each:
            # 开始随机的选区点，开始裁切，裁切的方法很简单，就是numpy的切片
            random_width = random.randint(0, x_width - img_w)
            random_height =random.randint(0,x_height - img_h)

            # 从height开始切，这里注意
            src_roi = src_imag[random_height:random_height +img_h, random_width, random_width + img_w]
            label_roi = label_imag[random_height:random_height +img_h, random_width, random_width + img_w]
            
            if mode == 'augment': # 如果模式是增强模式，那么使用数据增强，这里的参数化程序设计非常值得学习
                src_roi, label_roi = data_augment(src_roi, label_roi)

            cv.imwrite(('./train_src/{}.png'.format(g_count), src)
            cv.imwrite(('./train_src/{}.png'.format(g_count), src)

            count += 1
            g_count += 1












In [21]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
a[0,:]


[[1 2 3]
 [4 5 6]]


array([1, 2, 3])